### ISSUE TITLE
lbryum8 frequently falls behind, requires restart

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbryum-server#42]
This happened several times in the last few days.

**Comment by eukreign** [comment]
@shyba @lyoshenka @tzarebczan does this happen with lbryumx?

**Comment by shyba** [comment]
I think it's too early to tell, but I believe only a hard crash on the
synchronization would make it fall behind. Maybe open there when/if it
happens?

Em qua, 13 de jun de 2018 00:06, Lex Berezhny <notifications@github.com>
escreveu:
