### ISSUE TITLE
getvalueforuri returns a claim specified by id when the name does not match

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum-server#43]
Given a uri `<name>#<claim_id>`, a claim will be returned if one exists for the `claim_id` regardless of if this claim is for `name`.

**Comment by hackrush01** [comment]
Related: https://github.com/lbryio/lbryum/issues/190

**Comment by jackrobison** [comment]
lbryum client should also be updated to return an error upon receiving a response with a mismatched name
