### ISSUE TITLE
Install process fails

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbryum-server#47]
The lbryum-server install process fails with this requirement.

> Searching for lbryschema==0.0.15rc2
> Reading https://pypi.python.org/simple/lbryschema/
> Couldn't find index page for 'lbryschema' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> No local packages or download links found for lbryschema==0.0.15rc2
> error: Could not find suitable distribution for Requirement.parse('lbryschema==0.0.15rc2')

requirements.txt has this:

git+https://github.com/lbryio/lbryschema.git@v0.0.15rc2#egg=lbryschema

But the schema README suggests this. I replaced the original line with this and got a somewhat different error.

git+https://github.com/lbryio/lbryschema.git#egg=lbryschema

I git clone'd lbryschema, manually installed it, removed the reference from requirements.txt, and was able to complete the lbryum-server build.

The documentation at this point shows steps to create a SysV init and it references an executable 'electrum-server'.  Everything else I've seen from LBRY uses systemd rather than init, and the binary or script is nowhere to be found. I went digging for lbryum-server, poked around in the ~/lbryum-server/build directory tree, and I don't find it anywhere.

I would very much like to hear from the developer who works this issue - I'm D. Ray Blanco on Discord.

**Comment by eukreign** [comment]
Doesn't make sense to put effort into documenting / fixing lbryum-server at this point. Any future issues should go to https://github.com/lbryio/lbryumx.
