### ISSUE TITLE
Switch to electrumx (PLEASE DESTROY ME)

### ISSUE THREAD

**Issue by shyba** [lbryio/lbryum-server#54]
electrumx should be able to provide the same functionality except for specific commands added later, such as the ones used for claims. Electrumx is using Python 3 and known to be faster than the code which originated this repo, being a potential candidate for solving current performance issues.

- [x] Serialize/Deserialize Claimtrie transactions (Claim/update/support opcodes) -- 14 pts
    - [x] Implement a transaction serializer for recognizing claim opcodes and extracting values out - 5pts
	    - [x] Recognizing a claim transaction (see if it has the claim opcode) (Can be copied) - 2 pts
	    - [x] Implement the Serializer as electrumx deserializer subclass - 3 pts
    - [x] Refactor current code for being a library instead of a fork and push it to lbryumx repo - 6pts
        - [x] The refactor itself - 3 pts
        - [x] Figuring out how to make it run (injecting ourselves into coins.py?) - 3 pts
	- [x] Recognize the different block size and fields (done) - 0 pts
-------------
- [x] - Basic storage
  - [x] - Store Claim name basics (name, id, outpoint, ...) - 7 pts
    - [x] - Parse and store which claim is signed by which one - 5 pts
    - [x] - Detect abandons and trigger a DB delete - 2 pts
  - [x] - Update claim - 5 pts
    - [x] - make an update caused abandon become a real update
    - [x] - check if outpoint is valid
    - [x] - update claim info
  - [x] - Support claims - 5 pts
  - [x] - Undo information - 5 pts
    - [x] - Check how to fit that multi db updates with the cache and flush way of electrumx sync - 5 pts
 - [ ] - Consistency
    - [ ] - Full covering scenarios (abandons of supports, updates of supported claims and so on) - 0 pts (ongoing on all others)
    - [ ] - Check consistency against lbryum-server (also ongoing, unless a small automated script comes out) - 0 pts
----------------
- [x] Implementing a session and a new daemon (electrumx classes for adding commands and session stuff) - 1-2 days - 14 points
	- [x] blockchain.claimtrie.getclaimbyid (which uses get_claim_info, which is the most used function and requires storage) - 7 pts
	    - [x] Add storage for looking into name, value, outpoint, height and address - 5 pts
	    - [x] Implement the command itself and test it's output - 2 pts
	- [x] blockchain.claimtrie.getclaimssignedby (which requires signature handling and more storage) - 7 pts
	    - [x] Verify and store signed claims - 5 pts
	    - [x] Implement the command itself and test it's output - 2 pts
--------------
- [x] (depends on # 1) Import and fill storages -  1 week 
        - This needs another estimation round as part of it is done at the previous goal
	- [x] import and store claim information
		- [x] define data model (depends on the commands)
	- [x] signatures and parsing handling on import

- [x] Port basic claim commands - 1 week
	- Kinds: 1. simple daemon relayable 2. storage needs 3. claim protobuf parsing + signature checking
	- blockchain.claimtrie.getvalue
	- blockchain.claimtrie.getclaimsintx
	- blockchain.claimtrie.getclaimsforname
	- blockchain.claimtrie.getclaimbyid
	- blockchain.claimtrie.getclaimsbyids
	- blockchain.claimtrie.getnthclaimforname

- [x] add signature checking commands
	- blockchain.claimtrie.getclaimssignedby
	- blockchain.claimtrie.getclaimssignedbyid
	- blockchain.claimtrie.getclaimssignedbynthtoname

- [x] Undo (simple, but depends on # 1) - 1 day or less (just do # 2 inverse)

**Comment by shyba** [comment]
#1 Serialize/Deserialize Claimtrie transactions (Claim/update/support opcodes) -- 2-3 days
1. Recognizing a claim transaction (see if it has the claim opcode) (Can be copied)
2. Recogize the different block size and fields (done)
2. OpCodes (it's currently a hack)
2.2 The proper way is doing our own transaction serializer/deserializer (can be copied, probably from lbryum instead)

#2 (depends on #1) Import and fill storages -  1 week
1. import and store claim information
1.1 define data model (depends on the commands)
2. signatures and parsing handling on import

#3 Undo (simple, but depends on #1) - 1 day or less (just do #2 inverse)

#4 Implementing a session and a new daemon (electrumx classes for adding commands and session stuff) - 1-2 days
blockchain.claimtrie.getclaimbyid -> use it as a tracer bullet

#5 Port basic claim commands - 1 week
Kinds: 1. simple daemon relayable 2. storage needs 3. claim protobuf parsing + signature checking
blockchain.claimtrie.getvalue
blockchain.claimtrie.getclaimsintx
blockchain.claimtrie.getclaimsforname
blockchain.claimtrie.getclaimbyid
blockchain.claimtrie.getclaimsbyids
blockchain.claimtrie.getnthclaimforname
#6 add signature checking commands
blockchain.claimtrie.getclaimssignedby
blockchain.claimtrie.getclaimssignedbyid
blockchain.claimtrie.getclaimssignedbynthtoname
#7 add resolve related commands
blockchain.claimtrie.getvalueforuri
blockchain.claimtrie.getvaluesforuris

**Comment by lyoshenka** [comment]
dont forget about https://github.com/lbryio/lbryum-server/issues/49

**Comment by shyba** [comment]
New list:
## Testing
  - [x] - add support for regtest
  - [x] - generate a fixture using regtest
  - [ ] - test reorgs (undo) - 3 pts
  - [ ] - generate commands fixtures - 3 pts
  - [ ] - test basic commands - 5 pts
  - [ ] - test resolve command - 2 pts
## Implementation
  - [ ] - undo information - 5 pts
## unestimated extras (keep in mind list to move to sprint if it becomes feasible)
  - [ ] - add support address (https://github.com/lbryio/lbrycrd/issues/92) (this would change the command output, making it incompatible with current version)
  - [ ] - verify claim signatures during sync if it's fast enough - 5 pts
    - [ ] - improve lbryschema verification code with cryptography lib or make a binding to lbryschema.go
  - [ ] - make sure race conditions are fixed (client queries are made against flushed information) (that should be part of testing)

**Comment by shyba** [comment]
Closing as all missing issues are opened on their appropriate repo.
