### ISSUE TITLE
move re-usable lbry code into lbryschema

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbryum-server#61]
Move as much lbry specific code out of lbryum-server and into lbryschema. This will help with the electrumx port.

**Comment by shyba** [comment]
It is, but I would argue it doesn't match an issue, but a habit or an ongoing process. Do you agree @eukreign ? If so, we can close that and just keep this in mind (which I believe we already do since we get annoyed by duplicated code).

**Comment by shyba** [comment]
Oh, due the "help electrumx port" goal, I think it's done. The remaining scope is too broad.
